# Generated by Django 4.2.2 on 2023-07-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("WALLET_OWNER", "Wallet Owner")],
                default="WALLET_OWNER",
                max_length=25,
            ),
        ),
    ]
