# Generated by Django 4.2.2 on 2023-07-04 09:41

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=32,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
